import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import { 
  Bell, 
  AlertTriangle, 
  ShieldAlert, 
  Filter, 
  CheckCircle, 
  FileText, 
  ArrowRight,
  UserCheck
} from 'lucide-react';

export default function Alerts({ onSelectTransaction, onSelectCustomer, onCreateInvestigation }) {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [severityFilter, setSeverityFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState('');

  useEffect(() => {
    loadAlerts();
  }, [severityFilter, statusFilter]);

  const loadAlerts = async () => {
    try {
      setLoading(true);
      const data = await api.getAlerts({
        severity: severityFilter || undefined,
        status: statusFilter || undefined
      });
      setAlerts(data);
    } catch (err) {
      console.error("Failed to load alerts:", err);
    } finally {
      setLoading(false);
    }
  };

  const updateStatus = async (alertId, newStatus) => {
    try {
      await api.updateAlertStatus(alertId, newStatus);
      loadAlerts();
    } catch (err) {
      alert(`Error updating alert status: ${err.message}`);
    }
  };

  return (
    <div className="alerts-page">
      <div className="page-header">
        <div>
          <h1 className="page-title">Alert Triage & Priority Queue</h1>
          <p className="page-subtitle">Real-time alert queue generated by explainable rule violations</p>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="card" style={{ marginBottom: 20, padding: '12px 18px' }}>
        <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <Filter size={14} color="var(--text-muted)" />
            <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Filters:</span>
          </div>

          <select 
            className="select-field"
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
          >
            <option value="">All Severities</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
            <option value="LOW">Low</option>
          </select>

          <select 
            className="select-field"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          >
            <option value="">All Statuses</option>
            <option value="New">New</option>
            <option value="Acknowledged">Acknowledged</option>
            <option value="Investigating">Investigating</option>
            <option value="Closed">Closed</option>
          </select>

          <span style={{ marginLeft: 'auto', fontSize: '0.85rem', color: 'var(--text-muted)' }}>
            Showing <strong>{alerts.length}</strong> active alerts
          </span>
        </div>
      </div>

      {/* Alerts Grid / Feed */}
      {loading ? (
        <div className="card" style={{ textAlign: 'center', padding: 40, color: 'var(--text-muted)' }}>
          Loading risk alert stream...
        </div>
      ) : alerts.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: 40, color: 'var(--text-muted)' }}>
          No alerts match the chosen filters.
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {alerts.map((al) => (
            <div 
              key={al.alert_id} 
              className="card"
              style={{ 
                padding: '16px 20px', 
                borderLeft: `4px solid ${al.severity === 'CRITICAL' ? '#ef4444' : al.severity === 'HIGH' ? '#f97316' : '#eab308'}`,
                display: 'flex',
                flexDirection: 'column',
                gap: 12
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 10 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <span className={`risk-badge ${al.severity.toLowerCase()}`}>
                    {al.severity} ({al.risk_score})
                  </span>
                  <span style={{ fontSize: '1.05rem', fontWeight: 700, color: '#fff' }}>
                    {al.alert_type}
                  </span>
                  <span className={`status-badge ${al.status.toLowerCase().replace(' ', '-')}`}>
                    {al.status}
                  </span>
                </div>

                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                  {new Date(al.created_at).toLocaleString()}
                </div>
              </div>

              <div style={{ fontSize: '0.86rem', color: 'var(--text-secondary)', lineHeight: 1.45 }}>
                {al.details}
              </div>

              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12, paddingTop: 10, borderTop: '1px solid var(--border-color)' }}>
                <div style={{ display: 'flex', gap: 16, fontSize: '0.82rem', color: 'var(--text-secondary)' }}>
                  <span>
                    Customer: <strong style={{ color: 'var(--accent-blue)', cursor: 'pointer' }} onClick={() => onSelectCustomer(al.customer_id)}>{al.customer_name} ({al.customer_id})</strong>
                  </span>
                  <span>
                    Amount: <strong style={{ color: 'var(--text-primary)' }}>₹{al.transaction_amount?.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</strong>
                  </span>
                  <span>
                    Corridor: <strong style={{ color: 'var(--text-primary)' }}>{al.destination_country}</strong>
                  </span>
                </div>

                <div style={{ display: 'flex', gap: 8 }}>
                  <button 
                    className="btn btn-secondary btn-sm"
                    onClick={() => onSelectTransaction(al.transaction_id)}
                  >
                    View TXN {al.transaction_id} <ArrowRight size={12} />
                  </button>

                  {al.status !== 'Investigating' && (
                    <button 
                      className="btn btn-secondary btn-sm"
                      onClick={() => updateStatus(al.alert_id, 'Investigating')}
                    >
                      Mark Investigating
                    </button>
                  )}

                  {al.status !== 'Closed' && (
                    <button 
                      className="btn btn-secondary btn-sm"
                      onClick={() => updateStatus(al.alert_id, 'Closed')}
                    >
                      <CheckCircle size={12} /> Close
                    </button>
                  )}

                  <button 
                    className="btn btn-primary btn-sm"
                    onClick={() => onCreateInvestigation({
                      customer_id: al.customer_id,
                      full_name: al.customer_name,
                      primary_transaction_id: al.transaction_id,
                      summary: `Investigation triggered from Alert ${al.alert_id}: ${al.alert_type}`
                    })}
                  >
                    <FileText size={12} /> Escalate Case
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
